export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const GET_LIST_PAGE_SUCCESS = 'GET_LIST_PAGE_SUCCESS'

export const SET_PAGE = 'SET_PAGE'

export const GET_DETAIL_PROFILE_SUCCESS = 'GET_DETAIL_PROFILE_SUCCESS'

export const SET_CATCHED_POKEMON_SUCCESS = 'SET_CATCHED_POKEMON_SUCCESS'
export const SET_CATCHED_POKEMON_FAILED = 'SET_CATCHED_POKEMON_FAILED'
export const SET_CATCHED_POKEMON_RENAME = 'SET_CATCHED_POKEMON_RENAME'
